name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # Use the secret to assume the role
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Deploy to S3
        env:
          # Use the secret for the bucket name
          BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }} 
        run: |
          aws s3 sync ./frontend s3://$BUCKET_NAME --delete

      - name: Invalidate CloudFront Cache
        run: |
          DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'konstantinos.space')].Id | [0]" --output text)
          
          if [ "$DIST_ID" != "None" ] && [ "$DIST_ID" != "" ]; then
            echo "Found Distribution ID: $DIST_ID"
            aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
          else
            echo "CloudFront distribution for v2.konstantinos.space not found."
            exit 1
          fi