name: Deploy Backend & Infrastructure

on:
  push:
    branches:
      - main  
    paths:
      - 'infrastructure/**' # Only run if infrastructure changes
      - 'backend/**'        # or if Python code changes

permissions:
  id-token: write 
  contents: read

jobs:
  deploy-and-test:
    name: 'Deploy & Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure 

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to AWS using the OIDC Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::535462129366:role/GitHubDeployRole
          aws-region: us-east-1

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize Terraform 
      - name: Terraform Init
        run: terraform init

      # Apply Changes
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Capture the API URL from Terraform output
      - name: Get API URL
        id: get_url
        run: |
          echo "API_URL=$(terraform output -raw api_endpoint)" >> $GITHUB_ENV

      # Run the Python Smoke Test
      - name: Run Smoke Tests
        working-directory: ./backend 
        run: |
          pip install requests
          python Tests/Smoke_test.py
        env:
          # Pass the URL we captured in to the Python script
          API_URL: ${{ env.API_URL }}